[changelog]
header = ""
body = """
## {{ version }} – {{ timestamp | date(format="%d.%m.%Y") }}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message | trim }} ([{{ commit.id | truncate(length=7, end="") }}]({{ commit.id }}))
{% endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
tag_pattern = "v[0-9].*"
sort_commits = "newest"

commit_parsers = [
  { message = "^feat!", group = "⚠️ Breaking Changes" },
  { message = "^feat", group = "✨ Features" },
  { message = "^fix", group = "🐛 Bugfixes" },
  { message = "^perf", group = "⚡ Performance" },
  { message = "^refactor", group = "♻️ Refactoring" },
  { message = "^docs", group = "📝 Dokumentation" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore", group = "🔧 Sonstiges" },
]

[bump]
features_always_bump_minor = true
breaking_always_bump_major = true
